name: Validate PR source

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from dev
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "❌ Pull requests to main are only allowed from dev."
            exit 1
          fi
